<?php
// $Id$

/**
 * @file
 * An entity for TriVids athletes table
 *
 */

function trivids_entity_info(){
  $trivids_info['trivids'] = array(
    'label' => t('TriVids Athletes table'),
    'controller class' => 'TriVidsController',
    'base table' => 'trivids_athletes',
    'uri callback' => 'trivids_uri',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'idno',
    ),
    'static cache' => TRUE,
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'bundles' => array(
      'trivids'=> array(
        'label' => 'TriVids bundle thing',
        'admin' => array(
          'path' => 'admin/structure/trivids/manage',
          'access arguments' => array('administer trivids'),
        ),
      ),
    ),
    'view modes' => array(
      'full' => array(
        'label' => t('Full TriVids view mode'),
        'custom settings' =>  FALSE,
      ),
    )
  );
  
  return $trivids_info;
}


/**
 * Implements hook_uri().
 */
function trivids_uri($trivids){
  return array(
    'path' => 'trivids/' . $trivids->idno,
  );
}

/**
 * Implements hook_load()
 */
function trivids_load($idno = NULL, $reset = FALSE){
  $idnos = (isset ($idno) ? array($idno) : array());
  $trivids = trivids_load_multiple($idnos, $reset);
  return $trivids ? reset ($trivids) : FALSE;
}

/** 
 * Implements hook_load_multiple()
 */

function trivids_load_multiple($idnos = array(), $conditions = array(), $reset = FALSE){
  return entity_load('trivids', $idnos, $conditions, $reset);
}

/**
 * Implements hook_menu()
 */
function trivids_menu(){
  $items['admin/structure/trivids/manage'] = array(
    'title' => 'TriVids Admin',
    'description' => 'Manage TriVids structure',
    'page callback' => 'trivids_info',
    'access arguments' => array('administer trivids'),
  );
  $items['trivids/%trivids'] = array(
    'title callback' => 'trivids_page_title',
    'title arguments' => array(1),
    'page callback' => 'trivids_page_view',
    'page arguments' => array(1),
    'access arguments' => array('view trivids'),
    'type' => MENU_CALLBACK,
  );
/*
  $items['trivids/add'] = array(
    'title' => 'Add something TriVids!',
    'page callback' => 'trivids_add',
    'access arguments' => array('create trivids'),
  );
 */
  return $items;
}

/**
 * Implements hook_permission()
 */
function trivids_permission(){
    return array(
    'administer trivids' =>  array(
      'title' => t('Administer TriVids'),
      'restrict access' => TRUE,
    ),
    'view trivids' => array(
      'title' => t('View TriVids'),
    )
  );
}

/**
 * Implements hook_info()
 */
function trivids_info() {
  return ('Welcome to the administration page for TriVids entity!');
}

/**
 * Implements hook_page_title()
 */
function trivids_page_title($trivids){
  $title = 'Athlete id #:' . $trivids->idno;
  return $title;
}

/**
 * This is the page callback for rows in the data table
 */
function trivids_page_view($trivids, $view_mode = 'full'){
  // Our entity type, for convenience.
  $entity_type = 'trivids_basic';

  $trivids->content = array(
    '#view_mode' => $view_mode,
  );

  $trivids->content['idno'] = array(
    '#type' => 'item',
    '#title' => t('idno'),
    '#markup' => $trivids->idno,
  );
  $trivids->content['firstname'] = array(
    '#type' => 'item',
    '#title' => t('firstname'),
    '#markup' => $trivids->firstname,
  );
  $trivids->content['lastname'] = array(
    '#type' => 'item',
    '#title' => t('lastname'),
    '#markup' => $trivids->lastname,
  );
  $trivids->content['address'] = array(
    '#type' => 'item',
    '#title' => t('address'),
    '#markup' => $trivids->address,
  );
  $trivids->content['city'] = array(
    '#type' => 'item',
    '#title' => t('city'),
    '#markup' => $trivids->city,
  );
  $trivids->content['state'] = array(
    '#type' => 'item',
    '#title' => t('state'),
    '#markup' => $trivids->state,
  );
  $trivids->content['zip'] = array(
    '#type' => 'item',
    '#title' => t('zip'),
    '#markup' => $trivids->zip,
  );
  $trivids->content['age'] = array(
    '#type' => 'item',
    '#title' => t('age'),
    '#markup' => $trivids->age,
  );
  $trivids->content['sex'] = array(
    '#type' => 'item',
    '#title' => t('sex'),
    '#markup' => $trivids->sex,
  );
  $trivids->content['email'] = array(
    '#type' => 'item',
    '#title' => t('email'),
    '#markup' => $trivids->email,
  );

  // Build fields content.
  field_attach_prepare_view('trivids', array($trivids->idno => $trivids), $view_mode);
  entity_prepare_view('trivids', array($trivids->idno => $trivids));
  $trivids->content += field_attach_view('trivids', $trivids, $view_mode);

  return $trivids->content;
}

/**
 * Implements hook_field_extra_fields()
 */
function trivids_field_extra_fields() {
  $return = array();
  $return['trivids']['trivids'] = array(
    'form' => array(
      'idno' => array(
        'label' => t("The athlete's unique idno"),
        'description' => t('integer'),
        'weight' => 0,
      ),
    ),
  );

  return $return;
}

/**
 * Implements hook_add() 
 */
function trivids_add() {
  $trivids = (object) array (
    'idno' => '',
    'type' => 'trivids',
    'note' => '',
  );
  
  return drupal_get_form('trivids_add_form', $trivids);
}


/**
 * Implements hook_add_form() 
 */
function trivids_add_form($form, &$form_state, $trivids) {
  $form['note'] = array(
    '#type' => 'textfield',
    '#title' => t('Note'),
    '#required' => TRUE,
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  
  field_attach_form('trivids', $trivids, $form, $form_state);
  
  return $form;
}


/**
 * Implements hook_add_form_validate() 
 */
function trivids_add_form_validate($form, &$form_state) {
  $trivids_submisttion = (object) $form_state['values'];
  field_attach_form_validate('trivids', $trivids_submisttion, $form, $form_state);
}

/**
 * Implements hook_add_form_submit() 
 */
function trivids_add_form_submit($form, &$form_state) {
  $trivids_submission = (object) $form_state['values'];
  field_attach_submit('trivids', $trivids_submission, $form, $form_state);
  $trivids = trivids_save($trivids_submission);
  $form_state['redirect'] = "trivids/$trivids->idno";
}

/**
 * Implements hook_save() 
 */
function trivids_save(&$trivids) {
  return entity_get_controller('trivids')->save($trivids);
}

/**
 * Implements hook_views_api().
 */
function trivids_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'trivids') . '/views',
  );
}


